name: Rust 

on:
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:

   build:
    name: Build on Linux (Ubuntu)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
         ~/.cargo/bin/
         ~/.cargo/registry/index/
         ~/.cargo/registry/cache/
         ~/.cargo/git/db/
         target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Fetch Deps
      run: cargo fetch
    - name: Build Project
      run: cargo build --verbose -offline
    - name: Run Tests
      run: cargo test --verbose --all 
    - name: Run Clippy 
      run: cargo clippy --verbose -- -D warnings
